
name: C++ CI Workflow with conda-forge dependencies

on:
  pull_request:
  push:
  workflow_dispatch:


jobs:
  build:
    name: '[${{ matrix.os }}@${{ matrix.build_type }}@conda]'
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        build_type: [Release]
        os: [ubuntu-latest, windows-2022]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        channels: conda-forge,robostack-jazzy
        channel-priority: true
        conda-remove-defaults: true

    - name: Dependencies
      run: |
        conda install cxx-compiler cmake pkg-config make ninja colcon-common-extensions catkin_tools rosdep ros-jazzy-desktop yarp catch2

    - name: Environment [Linux]
      if: contains(matrix.os, 'ubuntu')
      run: |
        env
        conda list
        ros2 pkg list

    - name: Environment [Windows]
      if: contains(matrix.os, 'windows')
      shell: cmd /C CALL {0}
      run: |
        set
        conda list
        ros2 pkg list

    - name: Configure [Linux]
      if: contains(matrix.os, 'ubuntu')
      run: |
        mkdir -p build
        cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTING=ON ..

    - name: Configure [Windows]
      if: contains(matrix.os, 'windows')
      shell: cmd /C CALL {0}
      run: |
        mkdir -p build
        cd build
        cmake -G"Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTING=ON ..

    - name: Build [Linux]
      if: contains(matrix.os, 'ubuntu')
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}

    - name: Build [Windows]
      if: contains(matrix.os, 'windows')
      shell: cmd /C CALL {0}
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}

    - name: Test [Linux]
      if: contains(matrix.os, 'ubuntu')
      run: |
        cd build
        yarp namespace /test
        yarpserver --write &
        ctest --output-on-failure -C ${{ matrix.build_type }} .
        killall yarpserver

    - name: Test [Windows]
      if: contains(matrix.os, 'windows')
      shell: cmd /C CALL {0}
      run: |
        cd build
        yarp namespace /test
        cmd /c "START /B  yarpserver --write"
        ctest --output-on-failure -C ${{ matrix.build_type }} .
        set CTEST_ERROR=%ERRORLEVEL%
        taskkill /IM yarpserver.exe /F
        exit %CTEST_ERROR%
