
name: C++ CI Workflow with conda-forge dependencies

on:
  pull_request:
  workflow_dispatch:


jobs:
  build:
    name: '[${{ matrix.os }}@${{ matrix.build_type }}@conda]'
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        build_type: [Release]
        os: [ubuntu-latest, windows-2022]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        channels: conda-forge,robostack-humble
        channel-priority: true

    - name: Dependencies
      run: |
        # Workaround for https://github.com/conda-incubator/setup-miniconda/issues/186
        conda config --remove channels defaults
        conda install cxx-compiler cmake pkg-config make ninja colcon-common-extensions catkin_tools rosdep ros-humble-desktop yarp

    - name: Environment variables
      run: |
        env

    - name: Conda list
      run: |
        conda list

    - name: ROS2 pkg list
      run: |
        ros2 pkg list

    - name: Configure [Linux]
      if: contains(matrix.os, 'ubuntu')
      run: |
        mkdir -p build
        cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..

    - name: Configure [Windows]
      if: contains(matrix.os, 'windows')
      run: |
        mkdir -p build
        cd build
        cmake -G"Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..

    - name: Build
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}
